- name: now we are working to preparing the cart module
  hosts: Cart
  become: yes
  tasks:
    - name: here we are writing the disable the nodejs
      ansible.builtin.command: dnf module disable nodejs -y


    - name: here we are writing and enable the nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: here we are installing the nodejs module
      ansible.builtin.package:
       name: nodejs 
       state: present
    
    - name: here we are adding the usermodule
      ansible.builtin.user:
       name: roboshop 
       comment: system user
       shell: /sbin/nologin
       home: /app
    
    - name: here we are adding the properabsent directory here
      ansible.builtin.file:
       path: /app
       state: absent

    - name: here we are adding the proper directory here
      ansible.builtin.file:
       path: /app
       state: directory
   
    # - name: here we are removing the file
    #   ansible.builtin.file:
    #    path: /tmp/user.zip
    #    present: absent

      
    - name: here we are downloading the module
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
       dest: /tmp/cart.zip

    - name: here we are writing the unzip module
      ansible.builtin.unarchive:
       src: /tmp/cart.zip
       dest: /app
       remote_src: yes


    - name: Install  node.js package.
      community.general.npm:
       name: npm 
       path: /app


    - name: here we are writing the copy module
      ansible.builtin.copy:
       src: cart.service
       dest: /etc/systemd/system/cart.service


    - name: here we update the dameon reload one 
      ansible.builtin.systemd_service:
       name: daemon-reload
       state: started
       enabled: true