---
- name: Create AWS Key Pair
  hosts: localhost
  connection: local
  tasks:
    - name: Create SSH key pair
      amazon.aws.ec2_key:
        name: eswar-key
        state: present
        region: ap-south-1
      register: key_output

    - name: Save private key
      copy:
        content: "{{ key_output.key.private_key }}"
        dest: "~/.ssh/eswar-key.pem"
        mode: '0600'
      when: key_output.changed
