- name: here we insatalling the reddis server here
  hosts: reddis
  become: yes
  tasks:
    - name: here i am diable the reddis
      ansible.builtin.shell: dnf module disable redis -y

    - name: here i enable the reddis
      ansible.builtin.command: dnf module enable redis:7 -y

    - name: here we install the reddis
      ansible.builtin.service:
        name: reddis
        state: present

    - name: Replace old hostname with new hostname (requires Ansible >= 2.4)
      ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: '127.0.0.1 '
       replace: '0.0.0.0/0'


    - name: Disable Redis protected mode
      ansible.builtin.lineinfile:
       path: /etc/redis/redis.conf
       regexp: '^protected-mode '
       line: 'protected-mode no'
       

    - name: Enable and start MongoDB
      ansible.builtin.service:
        name: redis
        enabled: yes