- name: here we are writing the shipping module
  hosts: Shipping
  become: yes
  tasks:
    - name: here we are installing the maven and mysql
      ansible.builtin.dnf:
       name: "{{item}}"
       loop:
         - mysql
         - maven

    - name: here we are adding the user module here 
      ansible.builtin.user:
       name: roboshop 
       comment: system user
       shell: /sbin/nologin
       home: /app

    - name: here we are setting the path
      ansible.builtin.file:
       path: /app 
       state: directory
    
    - name: here we are downloading the values here 
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
       dest: /app


    - name: here we are unzip the modules
      ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes



    - name: here we are cleaing the packages
      ansible.buitin.command: mvn clean package 
      args:
       chdir: /app
    
    - name: now we are moving the zar files here
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 


    - name: here we are working on copying data
      ansible.builtin.copy:
       src: shipping.service
       dest: /etc/systemd/system/shipping.service

      
    - name: damon reload module
      ansible.builtin.systemd_service:
       name: user
       state: started
       enabled: true

    - name: exporting the data from mysql
      community.mysql.mysql_db:
       state: import
       name: all
       login_host: eswar.xyz
       login_user: root
       login_password: pRoboShop@1
       target: "{{}}"

       loop:
         - /app/db/schema.sql
         - /app/db/app-user.sql 
         - /app/db/master-data.sql