- name: setup shipping server
  hosts: shipping
  become: yes

  tasks:

    - name: install mysql and maven
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - mysql
        - maven



    - name: here we are installing the python librarie
      ansible.builtin.pip:
       executable: pip3.9
       name: "{{item}}"
      loop:
        - cryptography
        - PyMysql

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        comment: System user
        shell: /sbin/nologin
        home: /app

    - name: recreate app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: build the package
      ansible.builtin.shell: mvn clean package
      args:
        chdir: /app

    - name: rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copy shipping service file
      ansible.builtin.copy:
        src: Shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon reload & start service
      ansible.builtin.systemd_service:
        name: shipping
        state: started
        enabled: true
        daemon_reload: true

    - name: import mysql schema files
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: mysql.eswar.xyz
        login_user: root
        login_password: "RoboShop@1"
        target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql
        - /app/db/master-data.sql
